version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/topnal_demo_cicd
permissions:
  #set for project folder
  - object: /var/www
    pattern: "topnal_demo_cicd"
    owner: www-data #get from nginx.conf file
    group: www-data
    mode: 775
    type:
      - directory
  #set for file + folder in project 
  - object: /var/www/topnal_demo_cicd
    pattern: "**"
    owner: www-data #get from nginx.conf file
    group: www-data
    mode: 775
    type:
      - directory
      - file
hooks:
#  ApplicationStop:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  # During the AfterInstall deployment lifecycle event, run the commands 
  #   in the script specified in "location".
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ubuntu
  # During the ApplicationInstall deployment lifecycle event, run the commands 
  #   in the script specified in "location".
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ubuntu
#  ValidateService:
