// 01ED84Y9CGBBJZNNWVT1N8V2P0 : 01ED84Y9CGBBJZNNWVT1N8V2P0
module.exports = {
  verbose: true,
  // setupFiles: ['@babel/polyfill'],
  testEnvironment: 'node',
  // setupFilesAfterEnv: ['expect-more-jest', 'jest-extended'],
  // exclude: /(node_modules|bower_components|public\/)/,
  moduleDirectories: ['services', 'node_modules'],
  testMatch: ['<rootDir>/test/**/*.test.js'],
  transform: { '\\.js$': 'babel-jest' },
  restoreMocks: true,
  watchPlugins: [
    'jest-watch-suspend',
    ['jest-watch-toggle-config', { setting: 'bail' }],
    ['jest-watch-toggle-config', { setting: 'collectCoverage' }],
    ['jest-watch-toggle-config', { setting: 'notify' }],
    ['jest-watch-toggle-config', { setting: 'verbose' }],
    'jest-watch-typeahead/filename',
    'jest-watch-typeahead/testname',
  ],
  watchPathIgnorePatterns: [
    '<rootDir>/batch',
    '<rootDir>/coverage',
    '<rootDir>/data',
    '<rootDir>/flow-typed',
    '<rootDir>/infrastructure',
    '<rootDir>/lib',
    '<rootDir>/node_modules',
    '<rootDir>/public',
    '<rootDir>/scripts',
  ],
  collectCoverage: true,
  collectCoverageFrom: ['<rootDir>/services/**/*.js','<rootDir>/modules/request/*.js','<rootDir>/routes_es6/trendexpress.js'],
  coveragePathIgnorePatterns: ['<rootDir>/services/generate_scenario/*'],
  coverageDirectory: '<rootDir>/coverage',
  coverageReporters: ['lcov', 'text'],
  coverageThreshold: {
    global: { branches: 100, functions: 100, lines: 100, statements: 100 },
  },
  errorOnDeprecated: true,
};
